(dp1
S'output'
p2
S''
sS'layer'
p3
S'D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\applications\\Mestre/controllers/planoprova.py'
p4
sS'code'
p5
S"# coding: utf8\n# try something like\n   \n@auth.requires_login()\ndef cad_planoprova():\n    planoprova = SQLFORM(db.plano_de_prova)\n    if planoprova.accepts(request.vars,session):\n            redirect(URL(r=request,f='ver_planoprova'))\n    if planoprova.errors: response.flash='Erro em seu formul\xc3\xa1rio'\n    return dict(planoprova=planoprova)\n\ndef ver_planoprova():\n    row_planoprova=db().select(db.plano_de_prova.ALL)\n    return dict(row_planoprova=row_planoprova)\n\n\n@auth.requires_login()\ndef list_planodeprovas():\n   form=crud.create(db.plano_de_prova)\n   form2=crud.create(db.item_plano_de_prova)\n   professores=db(db.professor.id>0).select(db.professor.ALL)\n   planodeprovas=db(db.plano_de_prova.id>0).select(db.plano_de_prova.ALL,db.topico.ALL,db.taxionomia.ALL,db.dificuldade.ALL,db.item_plano_de_prova.ALL, left=db.item_plano_de_prova.on(db.item_plano_de_prova.plano_de_prova==db.plano_de_prova.id))\n   response.flash='Lista Plano de Prova'\n   return dict(professores=professores,planodeprovas=planodeprovas,form=form,form2=form2)\n\n@auth.requires_login()\ndef edit_planodeprova():\n   planodeprova_id=request.args(0)\n   planodeprova=db.plano_de_prova[planodeprova_id] or redirect(URL(r=request,f='../default/error'))\n   form=crud.update(db.plano_de_prova,planodeprova,next=url('list_planodeprovas'))\n   return dict(form=form)\n\nresponse._vars=response._caller(list_planodeprovas)\n"
p6
sS'traceback'
p7
S'Traceback (most recent call last):\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\gluon\\restricted.py", line 173, in restricted\n    exec ccode in environment\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\applications\\Mestre/controllers/planoprova.py", line 33, in <module>\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\gluon\\globals.py", line 96, in <lambda>\n    self._caller = lambda f: f()\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\gluon\\tools.py", line 1848, in f\n    return action(*a, **b)\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\applications\\Mestre/controllers/planoprova.py", line 22, in list_planodeprovas\n    planodeprovas=db(db.plano_de_prova.id>0).select(db.plano_de_prova.ALL,db.topico.ALL,db.taxionomia.ALL,db.dificuldade.ALL,db.item_plano_de_prova.ALL, left=db.item_plano_de_prova.on(db.item_plano_de_prova.plano_de_prova==db.plano_de_prova.id))\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\gluon\\sql.py", line 3023, in select\n    rows = response(query)\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\gluon\\sql.py", line 3018, in response\n    db._execute(query)\n  File "D:\\cefet\\2009.2, 2010.1\\LocalHostWeb2Py\\MESTRE-20100210\\web2py\\gluon\\sql.py", line 926, in <lambda>\n    self._execute = lambda *a, **b: self._cursor.execute(*a, **b)\n  File "C:\\Python26\\lib\\site-packages\\MySQLdb\\cursors.py", line 166, in execute\n    self.errorhandler(self, exc, value)\n  File "C:\\Python26\\lib\\site-packages\\MySQLdb\\connections.py", line 35, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1054, "Unknown column \'plano_de_prova.id\' in \'on clause\'")\n'
p8
s.